#!/bin/bash

if [[ $# -ne 2 ]]; then
 echo "usage: {crypt_dev_ID} {type:plain|luks|loopaes|tcrypt|bitlk}"
 exit 1
fi
sudo umount /dev/mapper/$1
sudo cryptsetup $2Close $1
if [[ $? -eq 0 ]]; then
 echo "vol unmounted and secured"
else
 echo "vol is still mounted/insecure"
 exit 1
fi

