#!/bin/bash

if [[ $# -lt 4 ]]; then
 echo "usage {encrypted_container} {crypt_dev_id} {mount_point} {keyfile}"
 exit 1
fi

sudo cryptsetup luksOpen $1 $2 --key-file $4
sudo mount -t auto /dev/mapper/$2 $3
if [[ $? -eq 0 ]]; then
 echo "$1 mounted successfully at $3"
 echo "crypt_dev_ID for unmounting and securing this vol ==> $2"
fi
