#!/bin/bash

GRN='\033[0;32m' # Green
RED='\033[0;31m'
PUR='\033[0;35m'
NC='\033[0m' # No Color

if [[ $# -lt 3 ]]; then
 echo "usage {encrypted_container} {crypt_dev_id} {mount_point}"
 exit 1
fi

sudo cryptsetup luksOpen $1 $2
sudo mount -t auto /dev/mapper/$2 $3
if [[ $? -eq 0 ]]; then
 echo -e "${PUR}$1${NC} mounted ${GRN}successfully${NC} at $3"
 echo -e "crypt_dev_ID for unmounting and securing this vol ==> ${PUR}$2${PUR}"
fi
